export const countries = [
  { code: "AF", name: "Afghanistan", namePt: "Afeganistão" },
  { code: "AL", name: "Albania", namePt: "Albânia" },
  { code: "DZ", name: "Algeria", namePt: "Argélia" },
  { code: "AD", name: "Andorra", namePt: "Andorra" },
  { code: "AO", name: "Angola", namePt: "Angola" },
  { code: "AG", name: "Antigua and Barbuda", namePt: "Antígua e Barbuda" },
  { code: "AR", name: "Argentina", namePt: "Argentina" },
  { code: "AM", name: "Armenia", namePt: "Armênia" },
  { code: "AU", name: "Australia", namePt: "Austrália" },
  { code: "AT", name: "Austria", namePt: "Áustria" },
  { code: "AZ", name: "Azerbaijan", namePt: "Azerbaijão" },
  { code: "BS", name: "Bahamas", namePt: "Bahamas" },
  { code: "BH", name: "Bahrain", namePt: "Bahrein" },
  { code: "BD", name: "Bangladesh", namePt: "Bangladesh" },
  { code: "BB", name: "Barbados", namePt: "Barbados" },
  { code: "BY", name: "Belarus", namePt: "Bielorrússia" },
  { code: "BE", name: "Belgium", namePt: "Bélgica" },
  { code: "BZ", name: "Belize", namePt: "Belize" },
  { code: "BJ", name: "Benin", namePt: "Benin" },
  { code: "BT", name: "Bhutan", namePt: "Butão" },
  { code: "BO", name: "Bolivia", namePt: "Bolívia" },
  { code: "BA", name: "Bosnia and Herzegovina", namePt: "Bósnia e Herzegovina" },
  { code: "BW", name: "Botswana", namePt: "Botsuana" },
  { code: "BR", name: "Brazil", namePt: "Brasil" },
  { code: "BN", name: "Brunei", namePt: "Brunei" },
  { code: "BG", name: "Bulgaria", namePt: "Bulgária" },
  { code: "BF", name: "Burkina Faso", namePt: "Burkina Faso" },
  { code: "BI", name: "Burundi", namePt: "Burundi" },
  { code: "KH", name: "Cambodia", namePt: "Camboja" },
  { code: "CM", name: "Cameroon", namePt: "Camarões" },
  { code: "CA", name: "Canada", namePt: "Canadá" },
  { code: "CV", name: "Cape Verde", namePt: "Cabo Verde" },
  { code: "CF", name: "Central African Republic", namePt: "República Centro-Africana" },
  { code: "TD", name: "Chad", namePt: "Chade" },
  { code: "CL", name: "Chile", namePt: "Chile" },
  { code: "CN", name: "China", namePt: "China" },
  { code: "CO", name: "Colombia", namePt: "Colômbia" },
  { code: "KM", name: "Comoros", namePt: "Comores" },
  { code: "CG", name: "Congo", namePt: "Congo" },
  { code: "CR", name: "Costa Rica", namePt: "Costa Rica" },
  { code: "HR", name: "Croatia", namePt: "Croácia" },
  { code: "CU", name: "Cuba", namePt: "Cuba" },
  { code: "CY", name: "Cyprus", namePt: "Chipre" },
  { code: "CZ", name: "Czech Republic", namePt: "República Tcheca" },
  { code: "DK", name: "Denmark", namePt: "Dinamarca" },
  { code: "DJ", name: "Djibouti", namePt: "Djibuti" },
  { code: "DM", name: "Dominica", namePt: "Dominica" },
  { code: "DO", name: "Dominican Republic", namePt: "República Dominicana" },
  { code: "EC", name: "Ecuador", namePt: "Equador" },
  { code: "EG", name: "Egypt", namePt: "Egito" },
  { code: "SV", name: "El Salvador", namePt: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea", namePt: "Guiné Equatorial" },
  { code: "ER", name: "Eritrea", namePt: "Eritreia" },
  { code: "EE", name: "Estonia", namePt: "Estônia" },
  { code: "ET", name: "Ethiopia", namePt: "Etiópia" },
  { code: "FJ", name: "Fiji", namePt: "Fiji" },
  { code: "FI", name: "Finland", namePt: "Finlândia" },
  { code: "FR", name: "France", namePt: "França" },
  { code: "GA", name: "Gabon", namePt: "Gabão" },
  { code: "GM", name: "Gambia", namePt: "Gâmbia" },
  { code: "GE", name: "Georgia", namePt: "Geórgia" },
  { code: "DE", name: "Germany", namePt: "Alemanha" },
  { code: "GH", name: "Ghana", namePt: "Gana" },
  { code: "GR", name: "Greece", namePt: "Grécia" },
  { code: "GD", name: "Grenada", namePt: "Granada" },
  { code: "GT", name: "Guatemala", namePt: "Guatemala" },
  { code: "GN", name: "Guinea", namePt: "Guiné" },
  { code: "GW", name: "Guinea-Bissau", namePt: "Guiné-Bissau" },
  { code: "GY", name: "Guyana", namePt: "Guiana" },
  { code: "HT", name: "Haiti", namePt: "Haiti" },
  { code: "HN", name: "Honduras", namePt: "Honduras" },
  { code: "HU", name: "Hungary", namePt: "Hungria" },
  { code: "IS", name: "Iceland", namePt: "Islândia" },
  { code: "IN", name: "India", namePt: "Índia" },
  { code: "ID", name: "Indonesia", namePt: "Indonésia" },
  { code: "IR", name: "Iran", namePt: "Irã" },
  { code: "IQ", name: "Iraq", namePt: "Iraque" },
  { code: "IE", name: "Ireland", namePt: "Irlanda" },
  { code: "IL", name: "Israel", namePt: "Israel" },
  { code: "IT", name: "Italy", namePt: "Itália" },
  { code: "JM", name: "Jamaica", namePt: "Jamaica" },
  { code: "JP", name: "Japan", namePt: "Japão" },
  { code: "JO", name: "Jordan", namePt: "Jordânia" },
  { code: "KZ", name: "Kazakhstan", namePt: "Cazaquistão" },
  { code: "KE", name: "Kenya", namePt: "Quênia" },
  { code: "KI", name: "Kiribati", namePt: "Kiribati" },
  { code: "KP", name: "North Korea", namePt: "Coreia do Norte" },
  { code: "KR", name: "South Korea", namePt: "Coreia do Sul" },
  { code: "KW", name: "Kuwait", namePt: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan", namePt: "Quirguistão" },
  { code: "LA", name: "Laos", namePt: "Laos" },
  { code: "LV", name: "Latvia", namePt: "Letônia" },
  { code: "LB", name: "Lebanon", namePt: "Líbano" },
  { code: "LS", name: "Lesotho", namePt: "Lesoto" },
  { code: "LR", name: "Liberia", namePt: "Libéria" },
  { code: "LY", name: "Libya", namePt: "Líbia" },
  { code: "LI", name: "Liechtenstein", namePt: "Liechtenstein" },
  { code: "LT", name: "Lithuania", namePt: "Lituânia" },
  { code: "LU", name: "Luxembourg", namePt: "Luxemburgo" },
  { code: "MK", name: "North Macedonia", namePt: "Macedônia do Norte" },
  { code: "MG", name: "Madagascar", namePt: "Madagascar" },
  { code: "MW", name: "Malawi", namePt: "Malawi" },
  { code: "MY", name: "Malaysia", namePt: "Malásia" },
  { code: "MV", name: "Maldives", namePt: "Maldivas" },
  { code: "ML", name: "Mali", namePt: "Mali" },
  { code: "MT", name: "Malta", namePt: "Malta" },
  { code: "MH", name: "Marshall Islands", namePt: "Ilhas Marshall" },
  { code: "MR", name: "Mauritania", namePt: "Mauritânia" },
  { code: "MU", name: "Mauritius", namePt: "Maurício" },
  { code: "MX", name: "Mexico", namePt: "México" },
  { code: "FM", name: "Micronesia", namePt: "Micronésia" },
  { code: "MD", name: "Moldova", namePt: "Moldávia" },
  { code: "MC", name: "Monaco", namePt: "Mônaco" },
  { code: "MN", name: "Mongolia", namePt: "Mongólia" },
  { code: "ME", name: "Montenegro", namePt: "Montenegro" },
  { code: "MA", name: "Morocco", namePt: "Marrocos" },
  { code: "MZ", name: "Mozambique", namePt: "Moçambique" },
  { code: "MM", name: "Myanmar", namePt: "Mianmar" },
  { code: "NA", name: "Namibia", namePt: "Namíbia" },
  { code: "NR", name: "Nauru", namePt: "Nauru" },
  { code: "NP", name: "Nepal", namePt: "Nepal" },
  { code: "NL", name: "Netherlands", namePt: "Países Baixos" },
  { code: "NZ", name: "New Zealand", namePt: "Nova Zelândia" },
  { code: "NI", name: "Nicaragua", namePt: "Nicarágua" },
  { code: "NE", name: "Niger", namePt: "Níger" },
  { code: "NG", name: "Nigeria", namePt: "Nigéria" },
  { code: "NO", name: "Norway", namePt: "Noruega" },
  { code: "OM", name: "Oman", namePt: "Omã" },
  { code: "PK", name: "Pakistan", namePt: "Paquistão" },
  { code: "PW", name: "Palau", namePt: "Palau" },
  { code: "PA", name: "Panama", namePt: "Panamá" },
  { code: "PG", name: "Papua New Guinea", namePt: "Papua-Nova Guiné" },
  { code: "PY", name: "Paraguay", namePt: "Paraguai" },
  { code: "PE", name: "Peru", namePt: "Peru" },
  { code: "PH", name: "Philippines", namePt: "Filipinas" },
  { code: "PL", name: "Poland", namePt: "Polônia" },
  { code: "PT", name: "Portugal", namePt: "Portugal" },
  { code: "QA", name: "Qatar", namePt: "Catar" },
  { code: "RO", name: "Romania", namePt: "Romênia" },
  { code: "RU", name: "Russia", namePt: "Rússia" },
  { code: "RW", name: "Rwanda", namePt: "Ruanda" },
  { code: "KN", name: "Saint Kitts and Nevis", namePt: "São Cristóvão e Nevis" },
  { code: "LC", name: "Saint Lucia", namePt: "Santa Lúcia" },
  { code: "VC", name: "Saint Vincent and the Grenadines", namePt: "São Vicente e Granadinas" },
  { code: "WS", name: "Samoa", namePt: "Samoa" },
  { code: "SM", name: "San Marino", namePt: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe", namePt: "São Tomé e Príncipe" },
  { code: "SA", name: "Saudi Arabia", namePt: "Arábia Saudita" },
  { code: "SN", name: "Senegal", namePt: "Senegal" },
  { code: "RS", name: "Serbia", namePt: "Sérvia" },
  { code: "SC", name: "Seychelles", namePt: "Seicheles" },
  { code: "SL", name: "Sierra Leone", namePt: "Serra Leoa" },
  { code: "SG", name: "Singapore", namePt: "Singapura" },
  { code: "SK", name: "Slovakia", namePt: "Eslováquia" },
  { code: "SI", name: "Slovenia", namePt: "Eslovênia" },
  { code: "SB", name: "Solomon Islands", namePt: "Ilhas Salomão" },
  { code: "SO", name: "Somalia", namePt: "Somália" },
  { code: "ZA", name: "South Africa", namePt: "África do Sul" },
  { code: "SS", name: "South Sudan", namePt: "Sudão do Sul" },
  { code: "ES", name: "Spain", namePt: "Espanha" },
  { code: "LK", name: "Sri Lanka", namePt: "Sri Lanka" },
  { code: "SD", name: "Sudan", namePt: "Sudão" },
  { code: "SR", name: "Suriname", namePt: "Suriname" },
  { code: "SZ", name: "Eswatini", namePt: "Eswatini" },
  { code: "SE", name: "Sweden", namePt: "Suécia" },
  { code: "CH", name: "Switzerland", namePt: "Suíça" },
  { code: "SY", name: "Syria", namePt: "Síria" },
  { code: "TW", name: "Taiwan", namePt: "Taiwan" },
  { code: "TJ", name: "Tajikistan", namePt: "Tajiquistão" },
  { code: "TZ", name: "Tanzania", namePt: "Tanzânia" },
  { code: "TH", name: "Thailand", namePt: "Tailândia" },
  { code: "TL", name: "Timor-Leste", namePt: "Timor-Leste" },
  { code: "TG", name: "Togo", namePt: "Togo" },
  { code: "TO", name: "Tonga", namePt: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago", namePt: "Trinidad e Tobago" },
  { code: "TN", name: "Tunisia", namePt: "Tunísia" },
  { code: "TR", name: "Turkey", namePt: "Turquia" },
  { code: "TM", name: "Turkmenistan", namePt: "Turcomenistão" },
  { code: "TV", name: "Tuvalu", namePt: "Tuvalu" },
  { code: "UG", name: "Uganda", namePt: "Uganda" },
  { code: "UA", name: "Ukraine", namePt: "Ucrânia" },
  { code: "AE", name: "United Arab Emirates", namePt: "Emirados Árabes Unidos" },
  { code: "GB", name: "United Kingdom", namePt: "Reino Unido" },
  { code: "US", name: "United States", namePt: "Estados Unidos" },
  { code: "UY", name: "Uruguay", namePt: "Uruguai" },
  { code: "UZ", name: "Uzbekistan", namePt: "Uzbequistão" },
  { code: "VU", name: "Vanuatu", namePt: "Vanuatu" },
  { code: "VA", name: "Vatican City", namePt: "Cidade do Vaticano" },
  { code: "VE", name: "Venezuela", namePt: "Venezuela" },
  { code: "VN", name: "Vietnam", namePt: "Vietnã" },
  { code: "YE", name: "Yemen", namePt: "Iêmen" },
  { code: "ZM", name: "Zambia", namePt: "Zâmbia" },
  { code: "ZW", name: "Zimbabwe", namePt: "Zimbábue" },
];

export function getCountryName(code: string, language: "pt-BR" | "en"): string {
  const country = countries.find((c) => c.code === code);
  if (!country) return code;
  return language === "pt-BR" ? country.namePt : country.name;
}
