import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

type Language = "pt-BR" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    "nav.dashboard": "Dashboard",
    "nav.offers": "Ofertas",
    "nav.domains": "Domínios",
    "nav.logs": "Logs",
    "nav.analytics": "Analytics",
    "nav.settings": "Configurações",
    "nav.admin": "Admin",
    "nav.admin.dashboard": "Dashboard",
    "nav.admin.users": "Usuários",
    "nav.admin.plans": "Planos",
    "nav.admin.billing": "Faturamento",
    "nav.admin.sharedDomains": "Domínios Compartilhados",
    "nav.admin.monitoring": "Monitoramento",
    "nav.admin.settings": "Configurações",
    "nav.backToUser": "Voltar ao Painel",
    "nav.logout": "Sair",
    "admin.monitoring.title": "Monitoramento do Sistema",
    "admin.monitoring.last72h": "Últimas 72 horas",
    "admin.monitoring.totalClicks": "Total de Cliques",
    "admin.monitoring.clicksDesc": "Cliques processados nas últimas 72h",
    "admin.monitoring.successRate": "Taxa de Sucesso",
    "admin.monitoring.successful": "Sucesso",
    "admin.monitoring.failed": "Falha",
    "admin.monitoring.avgResponseTime": "Tempo Médio de Resposta",
    "admin.monitoring.performance": "Performance",
    "admin.monitoring.performanceDesc": "Baseado no tempo médio de resposta",
    "admin.monitoring.excellent": "Excelente",
    "admin.monitoring.good": "Bom",
    "admin.monitoring.slow": "Lento",
    "admin.monitoring.clicksOverTime": "Cliques por Hora",
    "admin.monitoring.responseTimeOverTime": "Tempo de Resposta por Hora",
    "admin.monitoring.slowestRequests": "Requisições Mais Lentas",
    "admin.monitoring.responseTime": "Tempo de Resposta",
    "admin.monitoring.country": "País",
    "admin.monitoring.device": "Dispositivo",
    "admin.monitoring.date": "Data",
    "admin.monitoring.status": "Status",
    "admin.monitoring.error": "Erro",
    "admin.monitoring.noData": "Nenhum dado disponível",
    "dashboard.title": "Dashboard",
    "dashboard.todayClicks": "Clicks Hoje",
    "dashboard.totalClicks": "Clicks Totais",
    "dashboard.activeOffers": "Ofertas Ativas",
    "dashboard.activeDomains": "Domínios Ativos",
    "dashboard.clicksChart": "Clicks nos Últimos 7 Dias",
    "dashboard.clicksByOffer": "Clicks por Oferta",
    "dashboard.clicksByDomain": "Clicks por Domínio",
    "offers.title": "Ofertas",
    "offers.create": "Criar Oferta",
    "offers.edit": "Editar Oferta",
    "offers.name": "Nome da Oferta",
    "offers.slug": "Slug",
    "offers.platform": "Plataforma",
    "offers.domain": "Domínio",
    "offers.blackPage": "Página Black",
    "offers.whitePage": "Página White",
    "offers.countries": "Países",
    "offers.devices": "Dispositivos",
    "offers.status": "Status",
    "offers.active": "Ativo",
    "offers.inactive": "Inativo",
    "offers.xcode": "XCode",
    "offers.generatedUrl": "URL Gerada",
    "offers.clicks": "Clicks",
    "offers.noOffers": "Nenhuma oferta encontrada",
    "offers.delete": "Excluir Oferta",
    "offers.deleteConfirm": "Tem certeza que deseja excluir esta oferta?",
    "domains.title": "Domínios",
    "domains.add": "Adicionar Domínio",
    "domains.subdomain": "Subdomínio",
    "domains.status": "Status",
    "domains.verified": "Verificado",
    "domains.pending": "Pendente",
    "domains.error": "Erro",
    "domains.lastCheck": "Última Verificação",
    "domains.ssl": "SSL",
    "domains.noDomains": "Nenhum domínio encontrado",
    "domains.verifying": "Verificando...",
    "domains.checkNow": "Verificar Agora",
    "logs.title": "Logs",
    "logs.filter": "Filtrar",
    "logs.offer": "Oferta",
    "logs.domain": "Domínio",
    "logs.date": "Data",
    "logs.platform": "Plataforma",
    "logs.redirectType": "Tipo",
    "logs.black": "Black",
    "logs.white": "White",
    "logs.ip": "IP",
    "logs.userAgent": "User Agent",
    "logs.country": "País",
    "logs.device": "Dispositivo",
    "logs.timestamp": "Data/Hora",
    "logs.noLogs": "Nenhum log encontrado",
    "settings.title": "Configurações",
    "settings.account": "Conta",
    "settings.billing": "Pagamento",
    "settings.security": "Segurança",
    "settings.language": "Idioma",
    "settings.changePassword": "Alterar Senha",
    "settings.currentPassword": "Senha Atual",
    "settings.newPassword": "Nova Senha",
    "settings.confirmPassword": "Confirmar Senha",
    "settings.managePayment": "Gerenciar Pagamento",
    "settings.invoices": "Faturas",
    "settings.plan": "Plano",
    "settings.upgrade": "Fazer Upgrade",
    "settings.downgrade": "Fazer Downgrade",
    "admin.users.title": "Usuários",
    "admin.users.search": "Buscar usuário",
    "admin.users.email": "Email",
    "admin.users.plan": "Plano",
    "admin.users.clicks": "Clicks",
    "admin.users.status": "Status",
    "admin.users.actions": "Ações",
    "admin.users.suspend": "Suspender",
    "admin.users.activate": "Ativar",
    "admin.users.impersonate": "Acessar como",
    "admin.users.forcePayment": "Forçar Pagamento",
    "admin.users.addDays": "Adicionar Dias",
    "admin.users.changePlan": "Alterar Plano",
    "admin.plans.title": "Planos",
    "admin.plans.create": "Criar Plano",
    "admin.plans.edit": "Editar Plano",
    "admin.plans.name": "Nome",
    "admin.plans.price": "Preço (R$)",
    "admin.plans.maxOffers": "Máx. Ofertas",
    "admin.plans.maxDomains": "Máx. Domínios",
    "admin.plans.maxClicks": "Máx. Clicks",
    "admin.plans.trial": "Trial",
    "admin.plans.trialDays": "Dias de Trial",
    "admin.plans.unlimited": "Ilimitado",
    "admin.settings.title": "Configurações Admin",
    "admin.settings.logo": "Logo",
    "admin.settings.logoHelp": "Tamanho recomendado: 200x50 pixels (PNG ou SVG)",
    "admin.settings.uploadLogo": "Enviar Logo",
    "admin.impersonating": "Você está logado como",
    "admin.returnToAdmin": "Voltar ao Admin",
    "auth.login": "Entrar",
    "auth.register": "Cadastrar",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.forgotPassword": "Esqueceu a senha?",
    "auth.loginWithGoogle": "Entrar com Google",
    "auth.noAccount": "Não tem conta?",
    "auth.hasAccount": "Já tem conta?",
    "auth.resetPassword": "Redefinir Senha",
    "auth.sendReset": "Enviar Link",
    "auth.trial": "7 dias grátis",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.create": "Criar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.copy": "Copiar",
    "common.copied": "Copiado!",
    "common.all": "Todos",
    "common.actions": "Ações",
    "common.yes": "Sim",
    "common.no": "Não",
    "common.confirm": "Confirmar",
    "notifications.accountSuspended": "Conta Suspensa",
    "notifications.paymentFailed": "Pagamento Falhou",
    "notifications.domainError": "Problema com Domínio",
    "notifications.clickLimitWarning": "Aviso de Limite de Clicks",
    "notifications.regularize": "Por favor, regularize sua conta",
    "plan.starter": "Starter",
    "plan.professional": "Professional",
    "plan.enterprise": "Enterprise",
    "plan.offers": "ofertas",
    "plan.domains": "domínios",
    "plan.clicks": "clicks/mês",
    "plan.current": "Plano Atual",
    "plan.select": "Selecionar",
    "nav.subscription": "Assinatura",
    "subscription.title": "Assinatura",
    "subscription.currentPlan": "Plano Atual",
    "subscription.yourUsage": "Seu Uso",
    "subscription.offersUsed": "Ofertas Utilizadas",
    "subscription.domainsUsed": "Domínios Utilizados",
    "subscription.clicksUsed": "Clicks Utilizados",
    "subscription.of": "de",
    "subscription.unlimited": "Ilimitado",
    "subscription.mostPopular": "Mais Popular",
    "subscription.freeTrial": "dias grátis",
    "subscription.month": "/mês",
    "subscription.upgrade": "Fazer Upgrade",
    "subscription.downgrade": "Fazer Downgrade",
    "subscription.cancel": "Cancelar Assinatura",
    "subscription.reactivate": "Reativar Assinatura",
    "subscription.managePayment": "Gerenciar Pagamento",
    "subscription.paymentHistory": "Histórico de Pagamentos",
    "subscription.noPayments": "Nenhum pagamento encontrado",
    "subscription.status.active": "Ativa",
    "subscription.status.trial": "Em Trial",
    "subscription.status.canceled": "Cancelada",
    "subscription.status.pastDue": "Pagamento Pendente",
    "subscription.status.inactive": "Inativa",
    "subscription.endsAt": "Acesso até",
    "subscription.renewsAt": "Renova em",
    "subscription.startTrial": "Iniciar Trial Grátis",
    "subscription.subscribe": "Assinar",
    "subscription.processing": "Processando...",
    "subscription.paymentSuccess": "Pagamento realizado com sucesso",
    "subscription.paymentFailed": "Falha no pagamento",
    "subscription.paymentPending": "Pagamento pendente",
    "device.smartphone": "Smartphone",
    "device.desktop": "Desktop",
    "device.tablet": "Tablet",
    "error.required": "Campo obrigatório",
    "error.invalidEmail": "Email inválido",
    "error.passwordMismatch": "Senhas não conferem",
    "error.slugExists": "Esta slug já existe neste domínio",
    "error.limitReached": "Limite atingido",
    "error.upgradeRequired": "Upgrade necessário",
  },
  "en": {
    "nav.dashboard": "Dashboard",
    "nav.offers": "Offers",
    "nav.domains": "Domains",
    "nav.logs": "Logs",
    "nav.analytics": "Analytics",
    "nav.settings": "Settings",
    "nav.admin": "Admin",
    "nav.admin.dashboard": "Dashboard",
    "nav.admin.users": "Users",
    "nav.admin.plans": "Plans",
    "nav.admin.billing": "Billing",
    "nav.admin.sharedDomains": "Shared Domains",
    "nav.admin.monitoring": "Monitoring",
    "nav.admin.settings": "Settings",
    "nav.backToUser": "Back to Panel",
    "nav.logout": "Logout",
    "admin.monitoring.title": "System Monitoring",
    "admin.monitoring.last72h": "Last 72 hours",
    "admin.monitoring.totalClicks": "Total Clicks",
    "admin.monitoring.clicksDesc": "Clicks processed in the last 72h",
    "admin.monitoring.successRate": "Success Rate",
    "admin.monitoring.successful": "Successful",
    "admin.monitoring.failed": "Failed",
    "admin.monitoring.avgResponseTime": "Avg Response Time",
    "admin.monitoring.performance": "Performance",
    "admin.monitoring.performanceDesc": "Based on average response time",
    "admin.monitoring.excellent": "Excellent",
    "admin.monitoring.good": "Good",
    "admin.monitoring.slow": "Slow",
    "admin.monitoring.clicksOverTime": "Clicks per Hour",
    "admin.monitoring.responseTimeOverTime": "Response Time per Hour",
    "admin.monitoring.slowestRequests": "Slowest Requests",
    "admin.monitoring.responseTime": "Response Time",
    "admin.monitoring.country": "Country",
    "admin.monitoring.device": "Device",
    "admin.monitoring.date": "Date",
    "admin.monitoring.status": "Status",
    "admin.monitoring.error": "Error",
    "admin.monitoring.noData": "No data available",
    "dashboard.title": "Dashboard",
    "dashboard.todayClicks": "Today's Clicks",
    "dashboard.totalClicks": "Total Clicks",
    "dashboard.activeOffers": "Active Offers",
    "dashboard.activeDomains": "Active Domains",
    "dashboard.clicksChart": "Clicks in the Last 7 Days",
    "dashboard.clicksByOffer": "Clicks by Offer",
    "dashboard.clicksByDomain": "Clicks by Domain",
    "offers.title": "Offers",
    "offers.create": "Create Offer",
    "offers.edit": "Edit Offer",
    "offers.name": "Offer Name",
    "offers.slug": "Slug",
    "offers.platform": "Platform",
    "offers.domain": "Domain",
    "offers.blackPage": "Black Page",
    "offers.whitePage": "White Page",
    "offers.countries": "Countries",
    "offers.devices": "Devices",
    "offers.status": "Status",
    "offers.active": "Active",
    "offers.inactive": "Inactive",
    "offers.xcode": "XCode",
    "offers.generatedUrl": "Generated URL",
    "offers.clicks": "Clicks",
    "offers.noOffers": "No offers found",
    "offers.delete": "Delete Offer",
    "offers.deleteConfirm": "Are you sure you want to delete this offer?",
    "domains.title": "Domains",
    "domains.add": "Add Domain",
    "domains.subdomain": "Subdomain",
    "domains.status": "Status",
    "domains.verified": "Verified",
    "domains.pending": "Pending",
    "domains.error": "Error",
    "domains.lastCheck": "Last Check",
    "domains.ssl": "SSL",
    "domains.noDomains": "No domains found",
    "domains.verifying": "Verifying...",
    "domains.checkNow": "Check Now",
    "logs.title": "Logs",
    "logs.filter": "Filter",
    "logs.offer": "Offer",
    "logs.domain": "Domain",
    "logs.date": "Date",
    "logs.platform": "Platform",
    "logs.redirectType": "Type",
    "logs.black": "Black",
    "logs.white": "White",
    "logs.ip": "IP",
    "logs.userAgent": "User Agent",
    "logs.country": "Country",
    "logs.device": "Device",
    "logs.timestamp": "Date/Time",
    "logs.noLogs": "No logs found",
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.billing": "Billing",
    "settings.security": "Security",
    "settings.language": "Language",
    "settings.changePassword": "Change Password",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmPassword": "Confirm Password",
    "settings.managePayment": "Manage Payment",
    "settings.invoices": "Invoices",
    "settings.plan": "Plan",
    "settings.upgrade": "Upgrade",
    "settings.downgrade": "Downgrade",
    "admin.users.title": "Users",
    "admin.users.search": "Search user",
    "admin.users.email": "Email",
    "admin.users.plan": "Plan",
    "admin.users.clicks": "Clicks",
    "admin.users.status": "Status",
    "admin.users.actions": "Actions",
    "admin.users.suspend": "Suspend",
    "admin.users.activate": "Activate",
    "admin.users.impersonate": "Access as",
    "admin.users.forcePayment": "Force Payment",
    "admin.users.addDays": "Add Days",
    "admin.users.changePlan": "Change Plan",
    "admin.plans.title": "Plans",
    "admin.plans.create": "Create Plan",
    "admin.plans.edit": "Edit Plan",
    "admin.plans.name": "Name",
    "admin.plans.price": "Price ($)",
    "admin.plans.maxOffers": "Max Offers",
    "admin.plans.maxDomains": "Max Domains",
    "admin.plans.maxClicks": "Max Clicks",
    "admin.plans.trial": "Trial",
    "admin.plans.trialDays": "Trial Days",
    "admin.plans.unlimited": "Unlimited",
    "admin.settings.title": "Admin Settings",
    "admin.settings.logo": "Logo",
    "admin.settings.logoHelp": "Recommended size: 200x50 pixels (PNG or SVG)",
    "admin.settings.uploadLogo": "Upload Logo",
    "admin.impersonating": "You are logged in as",
    "admin.returnToAdmin": "Return to Admin",
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.loginWithGoogle": "Login with Google",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.resetPassword": "Reset Password",
    "auth.sendReset": "Send Link",
    "auth.trial": "7 days free",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.copy": "Copy",
    "common.copied": "Copied!",
    "common.all": "All",
    "common.actions": "Actions",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "notifications.accountSuspended": "Account Suspended",
    "notifications.paymentFailed": "Payment Failed",
    "notifications.domainError": "Domain Issue",
    "notifications.clickLimitWarning": "Click Limit Warning",
    "notifications.regularize": "Please regularize your account",
    "plan.starter": "Starter",
    "plan.professional": "Professional",
    "plan.enterprise": "Enterprise",
    "plan.offers": "offers",
    "plan.domains": "domains",
    "plan.clicks": "clicks/month",
    "plan.current": "Current Plan",
    "plan.select": "Select",
    "nav.subscription": "Subscription",
    "subscription.title": "Subscription",
    "subscription.currentPlan": "Current Plan",
    "subscription.yourUsage": "Your Usage",
    "subscription.offersUsed": "Offers Used",
    "subscription.domainsUsed": "Domains Used",
    "subscription.clicksUsed": "Clicks Used",
    "subscription.of": "of",
    "subscription.unlimited": "Unlimited",
    "subscription.mostPopular": "Most Popular",
    "subscription.freeTrial": "days free",
    "subscription.month": "/month",
    "subscription.upgrade": "Upgrade",
    "subscription.downgrade": "Downgrade",
    "subscription.cancel": "Cancel Subscription",
    "subscription.reactivate": "Reactivate Subscription",
    "subscription.managePayment": "Manage Payment",
    "subscription.paymentHistory": "Payment History",
    "subscription.noPayments": "No payments found",
    "subscription.status.active": "Active",
    "subscription.status.trial": "On Trial",
    "subscription.status.canceled": "Canceled",
    "subscription.status.pastDue": "Past Due",
    "subscription.status.inactive": "Inactive",
    "subscription.endsAt": "Access until",
    "subscription.renewsAt": "Renews on",
    "subscription.startTrial": "Start Free Trial",
    "subscription.subscribe": "Subscribe",
    "subscription.processing": "Processing...",
    "subscription.paymentSuccess": "Payment successful",
    "subscription.paymentFailed": "Payment failed",
    "subscription.paymentPending": "Payment pending",
    "device.smartphone": "Smartphone",
    "device.desktop": "Desktop",
    "device.tablet": "Tablet",
    "error.required": "Required field",
    "error.invalidEmail": "Invalid email",
    "error.passwordMismatch": "Passwords don't match",
    "error.slugExists": "This slug already exists on this domain",
    "error.limitReached": "Limit reached",
    "error.upgradeRequired": "Upgrade required",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      if (saved === "pt-BR" || saved === "en") {
        return saved;
      }
    }
    return "pt-BR";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
